spring.application.name=mail-service

server.port=9000

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=mail

spring.profiles.active=local

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.prometheus.enabled=true

logging.file.name=D:/Home/apps/alloy-windows/logs/main-app.log



google.oauth.credentials=classpath:credentials.json

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-5-nano

spring.http.clients.imperative.factory=jdk